hw1
QuantuM1o1/Tinkoff2024Homeworks pull request #1
Opened 2024-02-18 09:45 UTC by QuantuM1o1

2024-02-18 15:21 UTC, iskanred commented
Лучше юнит-тесты класть по такому же пути, что и сами тестируемые классы только в папке tests

https://stackoverflow.com/questions/3615006/unit-tests-must-locate-in-the-same-package

2024-02-19 12:39 UTC, QuantuM1o1 commented
> Лучше юнит-тесты класть по такому же пути, что и сами тестируемые классы только в папке tests
> 
> https://stackoverflow.com/questions/3615006/unit-tests-must-locate-in-the-same-package

fixed

2024-02-19 19:22 UTC, iskanred commented on bot/src/main/java/edu/java/bot/bot/TelegramBotImpl.java
> +public class TelegramBotImpl implements Bot {
немного путано с названиями

лучше просто вынести `Bot` и `TelegramBotImpl` в отдельный пакет `service` и назвать `BotService` `TelegramBotService`, при этом поставить аннотацию `@Service` над TelegramBotService

Благодаря этой аннотации бин создаться, как и `@Component` и не нужно будет его прописывть в конфигурации отдельно

подробно: https://otus.ru/nest/post/2577/

2024-02-19 20:06 UTC, iskanred requested changes
комменты относятся ко многим классам / методам, просто не стал дублировать

по тестам еще хочется увидеть теста бота и user message processor

В целом круто сделал! Понравилась твоя архитектура! 🔥
💯 8/8
Опирайся на комментарии, учитывай их в будущем, успешно выполняй домашки и дальше буду ставить 8/8 😁

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/TelegramBotConfig.java
> +public class TelegramBotConfig {
В конфигурацию обычно выносят классы, над которым нет контроля (библиотечные классы); либо для которых нужно несколько инстансов (bot1, bot2 с разными настройками)

У тебя есть контроль над классом, можешь у него поставить `@Component`, но еще лучше будет `@Service`, об этом писал)

подробно: https://www.baeldung.com/spring-component-annotation

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/bot/TelegramBotImpl.java
> +        bot = new TelegramBot(applicationConfig.telegramToken());
в конструкторе ко всем полям класса лучше обращаться через `this`, а еще лучше не только в конструкторе)

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/bot/TelegramBotImpl.java
> +public class TelegramBotImpl implements Bot {
немного путано с названиями

лучше просто вынести Bot и TelegramBotImpl в отдельный пакет service и назвать BotService TelegramBotService, при этом поставить аннотацию `@Service` над TelegramBotService

Благодаря этой аннотации бин создаться, как и `@Component` и не нужно будет его прописывть в конфигурации отдельно

подробно: https://otus.ru/nest/post/2577/

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/bot/TelegramBotImpl.java
> +        return this.bot.execute(request);
например, тут поставил `this`, а в методах `process` и `start` нет)

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/bot/TelegramBotImpl.java
> +    @PreDestroy
мощно 😎

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/HelpCommand.java
> +        return "/help";
вероятно, стоит вынести в отдельные статические переменные

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/ListCommand.java
> +            StringBuilder messageText = new StringBuilder("Tracked URLs:\n");
работа со строками - это отдельная функциональность, которая идет вперемешку с основной бизнес-логикой метода, тяжеловато читать

вынеси, пожалуйста, работу со строками в отдельнвый приватный метод типа такого:
```
return trackedUrlsMessage(trackedURLs); // вызовой этого приватного метода
```

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/StartCommand.java
> +        }
Можешь присмотреться к методу `putIfAbsent` и завязаться на его возвращаемые значения https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#putIfAbsent-K-V-

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/StartCommand.java
> +        String response;
лучше сразу делать return и не заводить под response отдельную переменную, тяжелее читать + есть вероятность где-то в методе его изменить два раза или забыть присвоить что-либо

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/TrackCommand.java
> +        }
многовато ветвлений, попробуй побить всю логику на несколько функций, например `getMessageFromUpdate`, который бы бросал исключение, если message неверный

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/TrackCommand.java
> +        Pattern pattern = Pattern.compile("^https?://\\S+$");
может лучше хранить объект типа `URI` в юзере и завязаться на его проверку?

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/userMessages/UserMessageProcessorImpl.java
> +@Component
Можно использовать `@Service`)

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/userMessages/UserMessageProcessorImpl.java
> +        this.commands.add(new StartCommand(usersMap));
В этом классе передать список команд можно в в конструкторе, а Spring сам заинжектит в этот список все бины (подробнее [тут](https://www.baeldung.com/spring-injecting-collections#reference), 5й раздел)

т.е. вручную лист наполнять необязательно)

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/userMessages/UserMessageProcessorImpl.java
> +        SendMessage response = null;
опять же лучше сразу делать `return new SendMessage(...)`

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/UnknownCommand.java
> +public class UnknownCommand implements Command {
мне кажется, overengineering + это не компонент + нулловые методы - такое себе)

можно просто в `UserMessageProcessorImpl` вернуть "Command is unknown`, будет понятнее)

А этот класс можно и удалить тогда 😓

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/dto/ChatUser.java
> +public record ChatUser(
👍

2024-02-19 20:06 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/HelpCommandTest.java
> +    void description() {
чутк избыточный тест, завтра изменится описание команды и тест придется подгонять, не очень хорошая вещь)

т.е. тут мы просто проверяем, что текст переменной в классе дейтсвительно равен этой строке, но это необязательно)

2024-02-19 20:06 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/HelpCommandTest.java
> +        assertThat(answer).isEqualTo("""
тут тоже немного избыточно)

можем просто проверить, что `answer` содержит строки `/start` и `/help`

2024-02-19 20:06 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/Command.java
> +    String command();
command.command() 😄
лучше назвать метод `name()`)

2024-02-19 20:06 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/ListCommandTest.java
> +    private Map<Long, ChatUser> usersMap;
создание мапы можно вынести в метод `setUp()`, аннотированный `@BeforeEach`
https://habr.com/ru/articles/590741/

2024-02-19 20:06 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/ListCommandTest.java
> +            - https://edu.tinkoff.ru
тут тоже можно просто проверить, что ответ содержит ссылку, а не точное сравнение

2024-02-19 20:06 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/ListCommandTest.java
> +        list.add("https://edu.tinkoff.ru");
ссылку лучше вынести в отдельную переменную, вдруг тут будет одно значение, а в проверке другое -> тест не пройдет несмотря на корректность исполнения

2024-02-19 20:06 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/HelpCommandTest.java
> +    void handle() {
в названиях тестов лучше придерживаться конвенций:
https://www.baeldung.com/java-unit-testing-best-practices#3-test-case-naming-convention

2024-02-26 13:51 UTC, merged