hw9
QuantuM1o1/Tinkoff2024Homeworks pull request #10
Opened 2024-04-14 18:14 UTC by QuantuM1o1

2024-04-14 18:18 UTC, QuantuM1o1 commented
Общий дашборд:
![Dashboard01](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/134952720/c72d9337-8151-4bff-b2e0-9fdbe5a9c862)

Дашборд для бота:
![Dashboard02](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/134952720/fd5d04ed-4f94-4817-afcc-c2c0240dc6cf)

Новый график:
![Dashboard03](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/134952720/02f1a7b3-f18c-4059-b204-4b2995ee8bb2)

2024-04-30 21:21 UTC, iskanred requested changes
💯 Все очень круто! 6/6

Я бы еще тесты на кастомные метрики прикрутил, что counter инкрементится при таких-то обстоятельствах.

\+ пару комментов оставил, надо бы внести коррективы

Но в целом огонь 🔥

2024-04-30 21:21 UTC, iskanred commented on compose.yml
> +#      - prometheus_data:/prometheus
почему закомменчено? я бы вернул

2024-04-30 21:21 UTC, iskanred commented on bot/src/main/java/edu/java/bot/userMessages/UserMessageProcessorService.java
> +        this.processedMessagesCounter = meterRegistry.counter("processed_messages_total");
почемы бы не сделать бином? можно тогда откуда угодно получать и инкрементить, вместо того, чтобы инжектить registry, можно инжектить сразу метрику

2024-05-02 18:40 UTC, iskanred approved these changes
✅

2024-05-03 15:31 UTC, merged