Hw10
QuantuM1o1/Tinkoff2024Homeworks pull request #11
Opened 2024-04-21 10:28 UTC by QuantuM1o1

2024-05-01 15:38 UTC, iskanred requested changes
Ставлю 4/4, но предлагаю немного доработать, чтобы было по красоте. На твое усмотрение разумеется, сейчас все по условию сделано идеально 💯🔥

2024-05-01 15:38 UTC, iskanred commented on .github/workflows/bot.yml
> +      - name: Log in to the Container registry
Знаю, что в условии по-другому, но я бы рекомендовал выносить в отдельную job

тут job называется build и проект просто билдится и происходит jacoco, она, по-хорошему, не должна подразумевать build и пуш образов

На практике это всегда выносить в отдельную джобу, которую может понадобится скипнуть, или наоборот будет нужна только она

2024-05-01 15:38 UTC, iskanred commented on bot/Dockerfile
> +FROM openjdk:21
тебе перед этим всем нужен тут создать отдельный временный builder образ (слой), который будет билдить приложение.

сейчас полагаешься на то, что приложение сбилжено, но докерфайл не должен это полагаться, тем более, что target ты в гит не проливаешь

докер образ должен строиться исходя только из исходного кода приложения. Например, чтобы он в CI джобе биз прогона тестов и джоб билда мог построиться и сразу запушиться

https://docs.docker.com/build/building/multi-stage/

2024-05-01 15:38 UTC, iskanred commented on bot/Dockerfile
> +ENTRYPOINT java -jar bot.jar
лучше всегда делать массивом, а не строкой, так как может понадобится передача дополнительных аргументов

https://til.agile.esm.co.jp/posts/docker-entrypoint-that-takes-args-needs-to-be-array/#:~:text=Dockerfile's%20ENTRYPOINT%20instruction%20accepts%20both,is%20intended%20to%20take%20arguments.

2024-05-01 15:38 UTC, iskanred commented on bot/Dockerfile
> +WORKDIR /app/bot
я бы оставил либо /app либо /bot, все равно контейнер bot подразумевает за собой, что app ботовский, а не чей-то другой)

2024-05-03 17:41 UTC, QuantuM1o1 commented on .github/workflows/bot.yml
> +      - name: Log in to the Container registry
Вынес

2024-05-03 17:41 UTC, QuantuM1o1 commented on bot/Dockerfile
> +FROM openjdk:21
Сделано

2024-05-03 17:41 UTC, QuantuM1o1 commented on bot/Dockerfile
> +ENTRYPOINT java -jar bot.jar
fixed

2024-05-03 17:41 UTC, QuantuM1o1 commented on bot/Dockerfile
> +WORKDIR /app/bot
fixed)

2024-05-06 11:52 UTC, iskanred approved these changes
✅

2024-05-07 04:52 UTC, merged