Hw2
QuantuM1o1/Tinkoff2024Homeworks pull request #2
Opened 2024-02-25 13:38 UTC by QuantuM1o1

2024-02-29 21:44 UTC, iskanred requested changes
Классно сделал, применил интересные подходы (с тем же клиентом), но в целом решение эталонное, молодец! Есть некоторые недочеты, связанные просто с отсутствием опыта, но это придет!

Рекомендую недочеты в рамках этого же PR исправить и запросить у меня ревью  в гитхабе и/или написать в личку в телеге.

💯 6/6

2024-02-29 21:44 UTC, iskanred commented on pom.xml
> +
question: почему решил явно добавить?)

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/Client.java
> +}
Интересная реализация, не встречал такого)

А если допустим, нужно будет использовать несколько методов в рамках клиента (например: у гитхаба fetchRepository, fetchUser, fetch...)? Нужно будет получается под каждый метод реализацию интерфейса писать?

+ передавать аргументы строкой - вариант не очень, может понадобится передать числа или объекты сложные, все пихать в массив строк будет неудобно, ну и непонятно, что в каком порядке идет, можно сильно запутаться и потом долго дебажить.

В целом кажется, что такая реализация - оверхед, но все равно приемлемо. Однако тогда исправить нужно следующее:
1. Параметризировать интерфейс нужно не только Output объектом, но и Input, который бы передавали в качестве аргумента метода `fetch`
2. Нужно передавать тогда классы тогда надо будет называть `GitHubRepositoriesClient` и т.п. для указания того, что будешь фетчить конкретно.
3. Назвать сам интерфейс стоит `WebClient` или `AsyncClient` для указания на использования реактивного стека

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/Client.java
> +}
Интересная реализация, не встречал такого)

А если допустим, нужно будет использовать несколько методов в рамках клиента (например: у гитхаба fetchRepository, fetchUser, fetch...)? Нужно будет получается под каждый метод реализацию интерфейса писать?

+ передавать аргументы строкой - вариант не очень, может понадобится передать числа или объекты сложные, все пихать в массив строк будет неудобно, ну и непонятно, что в каком порядке идет, можно сильно запутаться и потом долго дебажить.

В целом кажется, что такая реализация - оверхед, но все равно приемлемо. Однако тогда исправить нужно следующее:
1. Параметризировать интерфейс нужно не только Output объектом, но и Input, который бы передавали в качестве аргумента метода `fetch`
2. Нужно передавать тогда классы тогда надо будет называть `GitHubRepositoriesClient` и т.п. для указания того, что будешь фетчить конкретно.
3. Назвать сам интерфейс стоит `AsyncClient` для указания на использования реактивного стека

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/GitHubClient.java
> +    }
Когда этот конструктор применяется?

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
можешь попробовать исопльзовать аннотацию `@NestedConfigurationProperties`

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +@EnableScheduling
Лучше поставить на `Scheduler` классом или над мэином

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    }
можешь не объявлять их как бины конфигурации, ты уже зарегстрировал их, как бины, поставив над классом аннотации `@Component`

если есть вопросы, как все это работает, можешь писать в личку в телеграме

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    @Autowired
в целом получается, что эта конфигурация не нужна, потому что `WebClient.builder()` можно напрямую получать, где требуется

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/dto/GitHubRepositoryDTO.java
> +public record GitHubRepositoryDTO(
Лучше исопльзовать нейминг `GitHubRepositoryResponse` или `GitHubRepositoryResponseDto`

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/dto/StackOverflowDTO.java
> +        }
можно сразу писать тип поля `OffsetDateTime`, Jackson сам десериализует лоногвый timestamp и приведет к `OffsetDateTime`

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +        LOGGER.info("Updater works!");
question: проверял, работает?

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +    private final static Logger LOGGER = LogManager.getLogger();
можешь попробовать использовать `log4j` аннотацию из `lombok`

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/resources/application.yml
> +    interval: 10000
можно задавать в удобном формае `10s`, например

вообще спринг сам может парсить строки в Duration

Для @Scheduled варианта можно сделать, например, вот так:
https://stackoverflow.com/questions/59786883/is-there-way-to-use-scheduled-together-with-duration-string-like-15s-and-5m

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
>      public record Scheduler(boolean enable, @NotNull Duration interval, @NotNull Duration forceCheckDelay) {
наверное вообще стоит объявить `SchedulerProperties` отдельно и поставить над ним аннотацию  
```java
@ConfigurationProperties(prefix = "app.scheduler")
public record Scheduler(...) { }
```

+ вообще можно вынести scheduler из `app`

2024-02-29 21:44 UTC, iskanred commented on scrapper/src/test/java/edu/java/dto/StackOverflowDTOTest.java
> +}
тогда тест тоже не особо нужен

2024-03-06 18:46 UTC, QuantuM1o1 commented on pom.xml
> +
Была изначально реализация перевода времени из Unix другая, и там ругалось

2024-03-06 18:46 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/clients/Client.java
> +}
fixed

2024-03-06 18:47 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/clients/GitHubClient.java
> +    }
Использовал в тестах, поменял на моки

2024-03-06 18:47 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +@EnableScheduling
fixed

2024-03-06 18:47 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    }
fixed

2024-03-06 18:47 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    @Autowired
fixed

2024-03-06 18:47 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/dto/GitHubRepositoryDTO.java
> +public record GitHubRepositoryDTO(
fixed

2024-03-06 18:48 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/dto/StackOverflowDTO.java
> +        }
fixed

2024-03-06 18:48 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +        LOGGER.info("Updater works!");
Работает)

2024-03-06 18:48 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +    private final static Logger LOGGER = LogManager.getLogger();
Не понял зачем, но добавил

2024-03-06 18:49 UTC, QuantuM1o1 commented on scrapper/src/main/resources/application.yml
> +    interval: 10000
fixed

2024-03-06 18:49 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
>      public record Scheduler(boolean enable, @NotNull Duration interval, @NotNull Duration forceCheckDelay) {
fixed

2024-03-06 18:49 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/dto/StackOverflowDTOTest.java
> +}
fixed

2024-03-09 00:46 UTC, iskanred requested changes
Внеси, пожалуйста, правки

2024-03-09 00:46 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/GitHubRepositoriesClient.java
> +        return this.webClient.get()
билдеры или такие цепочные вызовы лучше разделять новыми строками

```java
webClient
    .get()
    .uri()
    .retrieve()
    .bodyToMono()
```

2024-03-09 00:46 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/GitHubRepositoriesClient.java
> +public class GitHubRepositoriesClient implements AsyncClient<GitHubRepositoryResponse, String[]> {
почему решил оставить массив строк, а не писать dto для Request? Сделать объект `GitHubRepositoryRequest`? не советую оставлять текущую реализацию

2024-03-09 00:46 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +    private final static Logger LOGGER = LogManager.getLogger();
ну она логгер добавляет, почитай, что она делает)
https://projectlombok.org/api/lombok/extern/log4j/Log4j

можно вручную логгер не объявлять

2024-03-09 00:46 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfig.java
> +@Configuration
а если scheduler в бин отдельный не заворчаивать в этой конфигурации, не работает что ли? по идее `@configurationproperties` должна сама бином делать объект

2024-03-09 16:53 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +    private final static Logger LOGGER = LogManager.getLogger();
Работает, но идея ругается, что лог не объявлен. Я поэтому сразу и не понял)

2024-03-09 17:09 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfig.java
> +@Configuration
У меня spring не видит, и сам говорит, добавьте в конфигурацию создание бина "scheduler"

2024-03-09 17:11 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/clients/GitHubRepositoriesClient.java
> +public class GitHubRepositoriesClient implements AsyncClient<GitHubRepositoryResponse, String[]> {
Починил, сразу не понял. Да, так определённо лучше выглядит

2024-03-09 17:11 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/clients/GitHubRepositoriesClient.java
> +        return this.webClient.get()
fixed

2024-03-11 12:41 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfig.java
> +@Configuration
понял! ты прав 🔥

2024-03-11 12:42 UTC, iskanred approved these changes
✅

2024-03-11 14:59 UTC, merged