Hw3
QuantuM1o1/Tinkoff2024Homeworks pull request #3
Opened 2024-03-03 15:56 UTC by QuantuM1o1

2024-03-13 17:18 UTC, iskanred requested changes
🔥 Все сделано, но много непонятностей и много ненужного кода. Пока, может, тяжело дается использование спринга и факт того, что при грамотном расставлении аннотаций и понимании работы под капотом на абстрактном уровне, можно избавиться от кучи кода и спринг все сделает автоматически за тебя.

Например, различного рода валидации или сериализации.

+ Рекомендую во всех DTO использовать `record`, а не `class`  

Обрадовало наличие тестов на контроллеры! В целом все гуд, но нужно исправить код и увидишь, как все на самом деле просто и кратко.

Поэтому вноси правки, запрашивай ревью, будем смотреть!

✅ 6/6 за то, что все есть. Но все равно настоятельно рекомендую код исправить!

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/api/UpdatesApi.java
> +    }
question: это для чего и зачем default, если все равно дефолтная реализация пустая?

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/api/UpdatesApi.java
> +}
это все делается проще через аннотации без использования `NativeWebRequest`, почему вообще решил использовать нативный реквест? Это довольно таки низкоуровневая абстракция, к которой редко прибегают и только тогда, когда дейтсвительно нужно

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/apiException/UserNotFoundException.java
> +    private final List<Long> usersList;
почему лист, а не один юзер?)

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/client/LinksClient.java
> +                    .flatMap(errorResponse -> Mono.error(new Throwable(errorResponse.getExceptionMessage())))
почему именно в Throwable оборачиваешь? Можно кастомные excpetion также завести и кидать их, либо хотя бы просто в базовые Exception или RuntimeException

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/ControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
можно не оборачивать в `ResponseEntity`, а сразу возвращать response + добавить аннотации над методоами `@ResponseStatus`, спринг сам обернет в ResponseEntity, почитай про аннотацию

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/UpdatesController.java
> +    @Override
вот здесь можно поставить аннотацию `@PostMapping`, прописать путь, прописать какой media type должен принимать в себя метод (`consumes`) и т.п.

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/UpdatesController.java
> +    @Override
обычно у контроллеров нет интерфейса, либо если есть, то там просто пустые методы

а все аннотации уже в классе реалзиции

лучше вынеси сюда все анноташки и удали интерфейс, либо оставть просто с одним пустым методом `postUpdates`

2024-03-13 17:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/UpdatesController.java
> +    public ResponseEntity<Void> updatesPost(
нейминг обычно наоборот: `postUpdates`, чтобы был глагол в имени метода)

2024-03-13 17:18 UTC, iskanred commented on models/src/main/java/dto/AddLinkRequest.java
> +public class AddLinkRequest {
не думал сделать класс `record` из java 17? Не нужно было перепопределять equals, hashcode, toString и писать конструктор

2024-03-13 17:18 UTC, iskanred commented on models/src/main/java/dto/ApiErrorResponse.java
> +public class ApiErrorResponse {
здесь тоже лучше сделать `record`

2024-03-13 17:18 UTC, iskanred commented on models/src/main/java/utils/ApiUtil.java
> +public class ApiUtil {
этот класс станет ненужен после правок

если хочешь отправить пример респонса, то просто сделай заглушку и отправить пустой LinkReponse

2024-03-21 15:46 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/api/UpdatesApi.java
> +    }
fixed

2024-03-21 15:46 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/api/UpdatesApi.java
> +}
fixed

2024-03-21 15:46 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/apiException/UserNotFoundException.java
> +    private final List<Long> usersList;
fixed

2024-03-21 15:47 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/client/LinksClient.java
> +                    .flatMap(errorResponse -> Mono.error(new Throwable(errorResponse.getExceptionMessage())))
Метод onStatus запрашивает Throwable

2024-03-21 15:48 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/controller/ControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
Оставил только ResponseEntity<Void> для тестируемости, хотя по сути только статус код проверяю

2024-03-21 15:48 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/controller/UpdatesController.java
> +    @Override
fixed

2024-03-21 15:48 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/controller/UpdatesController.java
> +    public ResponseEntity<Void> updatesPost(
fixed

2024-03-21 15:48 UTC, QuantuM1o1 commented on models/src/main/java/dto/AddLinkRequest.java
> +public class AddLinkRequest {
fixed

2024-03-21 15:49 UTC, QuantuM1o1 commented on models/src/main/java/dto/ApiErrorResponse.java
> +public class ApiErrorResponse {
fixed

2024-03-21 15:49 UTC, QuantuM1o1 commented on models/src/main/java/utils/ApiUtil.java
> +public class ApiUtil {
fixed

2024-03-21 15:58 UTC, QuantuM1o1 commented
![image](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/134952720/f40fd696-701d-440a-91b3-a4a2ad4fab18)
![image](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/134952720/6e332278-d046-40cb-9704-6d17ce5da4d9)
![image](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/134952720/2d3c2c4f-b1e1-4c99-a813-0c10cf2db0b7)
![image](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/134952720/e3832a1e-27ca-4cc8-bb4f-82828da9f8ff)

2024-03-25 19:02 UTC, iskanred commented on bot/src/main/java/edu/java/bot/client/LinksClient.java
> +                    .flatMap(errorResponse -> Mono.error(new Throwable(errorResponse.getExceptionMessage())))
ну exception же подкласс throwable?

2024-03-25 19:06 UTC, iskanred approved these changes
пару замечаний и вопросик есть, в целом отлично!
✅

2024-03-25 19:06 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        @RequestBody RemoveLinkRequest removeLinkRequest) {
с отступами совсем беда что-то

2024-03-25 19:06 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +    @RequestMapping(
можно использовать `@DeleteMapping` и не пистать в параметрах аннотации метод. Такие аннотации есть для всех методов HTTP

2024-03-26 16:56 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        @RequestBody RemoveLinkRequest removeLinkRequest) {
fixed

2024-03-26 16:56 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +    @RequestMapping(
fixed

2024-03-26 16:56 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/client/LinksClient.java
> +                    .flatMap(errorResponse -> Mono.error(new Throwable(errorResponse.getExceptionMessage())))
fixed

2024-03-26 19:02 UTC, iskanred requested changes
одна правка требуется в нескольких местах, где есть работа со статусами в Mono)

2024-03-26 19:02 UTC, iskanred commented on bot/src/main/java/edu/java/bot/client/LinksClient.java
> +                    })
вместо этого всего, можно навесить несолько `onStatus` с соответствующими кодами:
```java
  .onStatus(
    HttpStatus.NOT_FOUND::equals,
    response -> response.bodyToMono(ApiErrorResponse.class).map(ChatIsNotFoundException::new)
)
```

2024-03-27 18:39 UTC, merged