hw4
QuantuM1o1/Tinkoff2024Homeworks pull request #4
Opened 2024-03-10 15:05 UTC by QuantuM1o1

2024-03-17 15:26 UTC, iskanred requested changes
🔥 7/8, нужно исправить тип данных URL поля в БД

пока отправляю на доработку, как внесешь правки, запрашивай ревью в гитхабе, поставлю 8/8)

2024-03-17 15:26 UTC, iskanred commented on migrations/sql/init_tables.sql
> +    url VARCHAR(255) NOT NULL,
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

вообще URL может в длину доходить до 2000, а иногда больше)

так что лучше поставтиь тип данных `TEXT` и не париться

2024-03-17 15:26 UTC, iskanred commented on scrapper/src/test/java/edu/java/scrapper/PostgresIntegrationTest.java
> +        assertThat(IntegrationTest.POSTGRES.getDatabaseName()).isEqualTo("scrapper");
`POSTGRES` поле должно быть доступно без обращения к родительскому классу)

+ я бы добавил прверку, что инстанс базы данных запущен
`POSTGRES.isRunning()`

2024-03-21 16:07 UTC, QuantuM1o1 commented on migrations/sql/init_tables.sql
> +    url VARCHAR(255) NOT NULL,
fixed

2024-03-21 16:07 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/scrapper/PostgresIntegrationTest.java
> +        assertThat(IntegrationTest.POSTGRES.getDatabaseName()).isEqualTo("scrapper");
fixed

2024-03-25 19:07 UTC, iskanred approved these changes
8/8 ✅

2024-03-27 18:39 UTC, merged