Hw5
QuantuM1o1/Tinkoff2024Homeworks pull request #5
Opened 2024-03-17 22:20 UTC by QuantuM1o1

2024-03-17 22:43 UTC, QuantuM1o1 commented
Замёрджил сюда неисправленные варианты из веток hw3 и hw4, потом конфликты зарезолвлю в пользу исправленных версий с мейна

2024-03-27 14:53 UTC, iskanred requested changes
Большая проделанная работа! 🔥

Надо бы исправить замечания, но когда без них?)

В общем, 7/8 пока что, потому что не хватило тестов на добавленные сервисы.

Вообще рекомендую архитектуру немного перестроить, чтобы она была хорошо расширяемой - минимизация действий и рисков при добавлении: нового ресурса (github, stackoverflow, ...), новых типов репозиториев (jpa, jdbc, jooq, ...), и т.п.

Для этого всего нужно предпочитать проперти-классы хардкоженным строкам (или статическим переменным) и опираться на интерфейсы, а не на реализации. Добиться нужно того, чтобы при добавлении нового типа ресурса или репозитория, ничего не нужно было изменять в текущих классах, а было бы достаточно написать новую реализацию уже определенного интерфейса и добавить вызов этой реализации в нужном сервисе. Ну и в проперти добавить всю инфу (url, regexp, название ресурса и т.д.). Реализации dto и клиентов - само собой. Таким образом, соблюдая Open/Close принцип мы закрываем Dependency Injection принцип из SOLID

Работу отрпавил на доработку в гитхабе и на портале. Как закончишь, присылай на ревью и там, и там. + Лучше еще напиши в телеге дополнительно. 

P.S. У меня еще вопрос. Ты когда собираешься мержить PR прошлые?) А то они копятся и копятся, с такой кучей веток, наверное, работать неудобно)

2024-03-27 14:53 UTC, iskanred commented on migrations/sql/hw5.sql
> +    site_name VARCHAR(255) NOT NULL
надо поменять на текст, длина ссылки может больше, чем 255. или тут имеется в виду название домена (host name)? если да, то менять не надо

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/dao/JdbcLinkDAO.java
> +    @Transactional
транзакции обычно на сервисном слое происходят и там где, действительно требуется.

проанализируй, в каких местах действительно нужен транзакционный вызов, а где не нужно - надо убрат

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/dao/JdbcLinkDAO.java
> +public class JdbcLinkDAO implements LinkDAO {
это все скорее репозитории, чем DAO

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkParser/GitHubRepositoryLinkParser.java
> +}
можешь поглядеть `@UtilityClass` анноташку в ломбоке. Но она вроде эксперементальная, так что смотри сам, использовать или нет)

а вообще такую логику всю выносить в сервисы и минимизировать кол-во статических утилитарных классов. Мы жа на спринге пишем))

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +            LinkResponse linkResponse = new LinkResponse();
можно сразу положить все поля в конструктор и сделать `LinkResponse` рекордом

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        boolean alreadyExists = checkIfLinkExists(tgChatId, addLinkRequest.getLink());
переменную можно не заводить

нужно либо сразу проверить и переназвать метод: `if (linkExists(...))`, либо сохранить метод `checkIfLinkExists`, но он должен будет бросать исключение `LinkAlreadyExistsException`

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/TgChatController.java
> +        return ResponseEntity.ok().build();
вообще кажется, что логику проверки ссылки на существование надо выносить в сервисный слой

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkParser/GitHubRepositoryLinkParser.java
> +        String patternString = "^https?://github\\.com/(.*)/(.*)$";
эту строку можно хранить снаружи метода в статическом финальном поле

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkParser/GitHubRepositoryLinkParser.java
> +        Pattern pattern = Pattern.compile(patternString);
наверное, даже паттерн можно вынести наружу

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkParser/StackOverflowQuestionLinkParser.java
> +public class StackOverflowQuestionLinkParser {
тут все те же замечания, что и к гитхаб парсеру

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +        List<LinkDTO> list = updaterService.findNLinksToUpdate(UPDATED_LINKS);
question: плохо понтяно, что это значит? почему 2?

Почему он не вытаскивает все ссылки, которые стоит обновить? ТИпа `findOutdatedLinks`?

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +                case 1: {
мб вынести значения в переменные отдельные?

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +        for (LinkDTO link : list) {
Можно вынести запрос на апдейт `checkForUpdate()` в общий интерфейс `UpdateChecker`, который потом реализовать двумя сервисами `GithubUpdateChecker` и `StackOverflowUpdateChecker`, которые будут в себе инкапсулировать уже соответствующие клиенты.

Тогд можно мапу доменов (url -> service), которые, кстати, тоже лучше хранить в пропертях:
```yaml
resources:
    github:
       base-url:
       domain:
       repo:
    stackoverlow:
      ....
```

В общем в зависимости от домена пришедшего урла выбирать нужный `updateChecker`:
```java
domainToUpdateCheckers[url.getHost()].checkForUpdate(url);
```

Над названием переменных нужно получше подумать только)

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +public class JdbcLinkService implements LinkService {
несмотря на ТЗ домашки, рекомендую каждый сервис сделать в количестве одного экземпляра, не разбивая на разные реализации репозиториев, чтобы соблюдать принцип инверсии зависимостей из `SOLID`. Высокоуровневая абстракция типа сервиса не должна зависить от деталий реализации низкоуровневой типа репозитория.

Т.е. лучше сделать единые интерфейсы `LinkRepository` и `ChatRepository`, а их уже реализовывать классами типа `JdbcLinkRepository`, `JooqLinkRepository`, `JpaLinkRepository` и т.д.

А в сервисах уже можно полагаться только на интерфейсы репозиториев. А выбирать конкретную реализацию можно через `@Qualifier`, `@Primary` или `@Conditional...` аннотации (как в 6й домашке)

Сырой `JpaReposiotry`, который заполняется спрингом, можно хранить инкапсулированным в наследника твоего репозитория

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +            if (url.startsWith("https://stackoverflow.com/")) {
строки лучше выносить в проперти классы.

Иначе будет неудобно добавлять новый ресурс. По поводу организаци пропертей раписал в комменте выше

Тут тоже можно попробовать сделать мапой или хотя switch-case

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcTgChatService.java
> +    JdbcUserDAO userRepository;
приватным не лучше сделать?)

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/test/java/edu/java/client/UpdatesClientTest.java
> +    private WireMockServer wireMockServer;
посмотри в сторону `@WebFluxTest`, мб пригодится и будет работать удобнее, но не гарантирую)

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/test/java/edu/java/client/UpdatesClientTest.java
> +@SpringBootTest
ты тут для теста поднимаешь весь контекст спринга => все бины, хотя используешь только один

Можно указать в этой анноташке списком все бины, которые нужны для теста

Сделай это, пожалуйста, для всех тестов, где эта аннотация используется

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/test/java/edu/java/controller/LinksControllerTest.java
> +    private AutoCloseable closeable;
название не очень говорящее)
непонятно, что закрывается

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/test/java/edu/java/controller/LinksControllerTest.java
> +
не пробовал использовать `@AutoConfigureMockMvc`?  Было бы проще, веротяно

2024-03-27 14:53 UTC, iskanred commented on scrapper/src/test/java/edu/java/dao/JdbcLinkDAOTest.java
> +    @Rollback
если аннотация у всех методов, можно перенести на уровень класса, как правило

+вроде же ее значение и так `true` по дефолту для spring test context:

> Rollback for integration tests in the Spring TestContext Framework defaults to `true` even if `@Rollback` is not explicitly declared.

https://docs.spring.io/spring-framework/reference/testing/annotations/integration-spring/annotation-rollback.html

2024-04-07 06:31 UTC, QuantuM1o1 commented on migrations/sql/hw5.sql
> +    site_name VARCHAR(255) NOT NULL
Тут имя домена, оставил, как есть

2024-04-07 06:31 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/dao/JdbcLinkDAO.java
> +    @Transactional
fixed

2024-04-07 06:31 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/dao/JdbcLinkDAO.java
> +public class JdbcLinkDAO implements LinkDAO {
fixed

2024-04-07 06:32 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkParser/GitHubRepositoryLinkParser.java
> +}
Убрал утилитарные классы

2024-04-07 06:33 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +            LinkResponse linkResponse = new LinkResponse();
fixed

2024-04-07 06:33 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        boolean alreadyExists = checkIfLinkExists(tgChatId, addLinkRequest.getLink());
fixed

2024-04-07 06:33 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/controller/TgChatController.java
> +        return ResponseEntity.ok().build();
fixed

2024-04-07 06:33 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkParser/GitHubRepositoryLinkParser.java
> +        String patternString = "^https?://github\\.com/(.*)/(.*)$";
Добавил в проперти

2024-04-07 06:34 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkParser/GitHubRepositoryLinkParser.java
> +        Pattern pattern = Pattern.compile(patternString);
Не совсем понял

2024-04-07 06:34 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkParser/StackOverflowQuestionLinkParser.java
> +public class StackOverflowQuestionLinkParser {
fixed

2024-04-07 06:34 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +        List<LinkDTO> list = updaterService.findNLinksToUpdate(UPDATED_LINKS);
Ограничение на вызовы от внешних апи, вынес параметр в настройки приложения

2024-04-07 06:35 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +                case 1: {
fixed

2024-04-07 06:35 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +        for (LinkDTO link : list) {
Кажется, сделал, как надо)

2024-04-07 06:36 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +public class JdbcLinkService implements LinkService {
Сделал, не понял, что потом будет с JPA, надо будет смотреть

2024-04-07 06:36 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +            if (url.startsWith("https://stackoverflow.com/")) {
fixed

2024-04-07 06:36 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcTgChatService.java
> +    JdbcUserDAO userRepository;
Постарался везде приватными сделать, надо будет в конце ещё раз пройтись

2024-04-07 06:37 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/client/UpdatesClientTest.java
> +    private WireMockServer wireMockServer;
Вообще убрал аннотации

2024-04-07 06:38 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/client/UpdatesClientTest.java
> +@SpringBootTest
Убрал, где получилось. В местах, где вызывается JdbcTemplate не смог, он не хочет подниматься

2024-04-07 06:38 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/controller/LinksControllerTest.java
> +    private AutoCloseable closeable;
fixed

2024-04-07 06:38 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/controller/LinksControllerTest.java
> +
fixed

2024-04-07 06:38 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/dao/JdbcLinkDAOTest.java
> +    @Rollback
fixed

2024-04-07 16:02 UTC, iskanred approved these changes
Оставил ответы к твоим комментам. В целом больше замечаний нет. Если захочешь еще что-то исправить, то норм, но ревью запрашивать больше не нужно)

💯 8/8 
✅

2024-04-07 16:02 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkUpdater/LinkUpdaterScheduler.java
> +        for (LinkDTO link : list) {
вроде да)

2024-04-07 16:02 UTC, iskanred commented on scrapper/src/main/java/edu/java/linkParser/GitHubRepositoryLinkParser.java
> +        Pattern pattern = Pattern.compile(patternString);
`Pattern` объект

2024-04-07 16:02 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +public class JdbcLinkService implements LinkService {
Можно в репозитории Jpa, которые будут реализовывать твой интерфейс, положить бины репозиториев Jpa, которые заполнит спринг:
```java
interface MyRepository { }

interface JpaEntity...Repository extends JpaRepository<...> { }

@Repository
class JpaMyRepository implements MyRepository {
    JpaEntity...Repository jpaRepository;
    ...
}

@Repository
class JdbcMyRepository implements MyRepository {
...
}
...
```

2024-04-08 15:21 UTC, merged