Hw5bonus
QuantuM1o1/Tinkoff2024Homeworks pull request #7
Opened 2024-03-25 10:03 UTC by QuantuM1o1

2024-03-27 15:03 UTC, iskanred commented
Привет! Что-то файлов в PR совсем много. Чем больше файлов, тем тяжелее проверять и тем меньше хорошего фидбека смогу оставить.

Когда сможем смержить PRы предыдущих домашек?

2024-03-27 15:25 UTC, iskanred requested changes
Все гуд! 👍

Комментарии за дз5 и бонус лучше воспринимай, как общие.

Рекомендую все висящие PR помержить,а потом выкатить PR с исправлениями. Но это если время есть, конечно.

Сильно рекомендую вынести реализации репозиториев под единым интерфейсом, чтобы не дублировать сервисы для каждой из реализацией, а то по факту они одинаковые + не дублировать тесты, когда добавишь их к предыдущей работе)
От этого сильно поменяется и дз 6, поэтому его у тебя буду проверять только в конце недели, мб успеешь внести правки до этого момента)

В целом за дз - 15 баллов. Но из-за большого опоздания снимаю 5. Итого: 10 баллов 🔥

В PR запрашиваю изменения, на портале работу принимаю

2024-03-27 15:25 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
>  @Component
я бы явно отметил, что это `@Service`

2024-03-27 15:25 UTC, iskanred commented on migrations/sql/init_tablesJOOQ.sql
> +    url VARCHAR(255) NOT NULL,
лушче исопльзовать тип данных текст, длина урла может больше 255

2024-03-27 15:25 UTC, iskanred commented on models/src/main/java/utils/ApiUtil.java
> +    public static void setExampleResponse(NativeWebRequest req, String contentType, String example) {
а зачем это нужно?

2024-03-27 15:25 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        return ResponseEntity.ok().body(response);
можно не оборачивать в `ReponseEntity`, спринг сам это сделает

Исправь везде, пожалуйста

2024-03-27 15:25 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        response.setSize(responseList.size());
многовато логики для контроллера, маппинг листа респонсов dto можно осуществить в сервисном слое, либо тут, но завести отдельный сервис-маппер

2024-04-14 07:36 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
>  @Component
fixed

2024-04-14 07:37 UTC, QuantuM1o1 commented on migrations/sql/init_tablesJOOQ.sql
> +    url VARCHAR(255) NOT NULL,
fixed

2024-04-14 07:37 UTC, QuantuM1o1 commented on models/src/main/java/utils/ApiUtil.java
> +    public static void setExampleResponse(NativeWebRequest req, String contentType, String example) {
removed

2024-04-14 07:37 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        return ResponseEntity.ok().body(response);
fixed

2024-04-14 07:37 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        response.setSize(responseList.size());
fixed

2024-04-15 11:36 UTC, iskanred requested changes
Правки нужны некоторые

Надо бы прихорошить тесты, но уже сейчас в целом проект выглядит красиво 🔥

За ДЗ 6 - 8/8 💯

2024-04-15 11:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/updateChecker/GithubUpdateChecker.java
> +        Pattern pattern = Pattern.compile(patternString);
можно сделать полем и инициализировать в конструкторе

2024-04-15 11:36 UTC, iskanred commented on scrapper/src/test/java/edu/java/service/GithubUpdateCheckerTest.java
> +        mockMap.put(linkDTO.domainName(), mockResource);
Общую часть можно вынести в поля класса и заполнять в `@BeforeEach` или `@BeforeAll` методах

2024-04-15 11:36 UTC, iskanred commented on scrapper/src/test/java/edu/java/service/LinkUpdaterServiceTest.java
> +        }
Если заохчешь в более функциональном виде написать
```java
IntStream.range(1, n).forEach (i ->
    mockList.add(mockLink)
)
```

2024-04-15 11:36 UTC, iskanred commented on scrapper/src/test/java/edu/java/service/GithubUpdateCheckerTest.java
> +        mockMap.put(linkDTO.domainName(), mockResource);
так во всех тест-классах

2024-04-15 11:36 UTC, iskanred commented on scrapper/src/main/java/edu/java/repository/jpa/JpaUserLinkRepositoryImpl.java
> +        this.jpaLinkRepository.saveAndFlush(linkEntity);
если несколько сейвов в одном методе, лучше сделать
```java
r.save(e1);
r.save(e2);
r.flush()
```
flush данные уже сливает в бд

https://www.baeldung.com/spring-jpa-flush

2024-04-20 13:15 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/service/updateChecker/GithubUpdateChecker.java
> +        Pattern pattern = Pattern.compile(patternString);
fixed

2024-04-20 13:15 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/service/GithubUpdateCheckerTest.java
> +        mockMap.put(linkDTO.domainName(), mockResource);
fixed

2024-04-20 13:15 UTC, QuantuM1o1 commented on scrapper/src/test/java/edu/java/service/LinkUpdaterServiceTest.java
> +        }
fixed

2024-04-20 13:16 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/repository/jpa/JpaUserLinkRepositoryImpl.java
> +        this.jpaLinkRepository.saveAndFlush(linkEntity);
Там же в разные репозитории запись идёт, где один репозиторий, сделал один flush()

2024-04-21 22:53 UTC, iskanred approved these changes
✅

2024-04-27 14:16 UTC, merged