Hw7
QuantuM1o1/Tinkoff2024Homeworks pull request #8
Opened 2024-03-31 19:18 UTC by QuantuM1o1

2024-04-18 22:31 UTC, iskanred requested changes
🔥 Все круто! Понравилась идея с наследованием от Reactor Retry, грамотно сделано! 

Советую еще глянуть bucket4j спринг бут стартер. Имлементить необязательно, но хотя бы, что он есть знать.

Не хватает только тестов на ретраи, но это добавтиь в твоей реализации недолго, просто сколько раз какой-то метод вызвался. Если придумаешь, как учитывать стратегию бэкоффа будет плюсом, но необязательно, потому что это уже слонжо. 

Поэтому пока 5/6. Отправляю на доработку в гитхабе и на портале)

Ну а если еще и bucket4j как-то протестить сможешь, будет вообще + в карму. Но это супер-необязательно, в т.ч. потому что сложно. Если время есть, попробуй для интереса)

Плюс, сейчас все параметры для ретраев у тебя стоят одни для всех клиентов. Хотя разные ресурсы (бот, гитхаб, стэк) могут отвечать с разной скоростью / разными статусами / быть не доступными. В общем лучше сделать так, чтобы можно было параметризировать политику ретраев для каждого клиента. В идеале, если еще и саму политику ретраев можно менять, например, одному ресурсу лучше linear retry, а другому - exponential или jitter. При было бы круто, если бы кол-во кода не возросло линейно. Можно иметь дефолтную родительскую реализацию политики ретраев и менять при необходимости или как-то по-другому сделать. Это необязательно, но было супер и приближенно к реальности!

В реальных проектах параметры ретраев относят к конфигу клиента:
```yaml
some-client:
    base-url: ...
    get-smth:
        url: ${base-url}/smth/
        ...
     retry-policy:
         backoff: 1s
         backoff-type: exponential
```

P.S. Прошу прощения за долгую проверку, был загружен

2024-04-18 22:31 UTC, iskanred commented on bot/pom.xml
> +        </dependency>
у bucket4j есть свой spring boot starter, который можно настроить через yaml конфиг и использовать встроенные аннотации. Так было бы попроще и поприятнее)

https://github.com/MarcGiffing/bucket4j-spring-boot-starter?tab=readme-ov-file#property-configuration-examples

2024-04-18 22:31 UTC, iskanred commented on bot/pom.xml
> +
question: а че зачем протобаф?)

2024-04-18 22:31 UTC, iskanred commented on bot/src/main/resources/application.yml
> +    - not_found
minor: я бы писал большими буквами, как оно выглядит в доках, либо коды)

2024-04-29 19:05 UTC, QuantuM1o1 commented on bot/pom.xml
> +        </dependency>
Добавил в боте, в скраппере из-за него падают тесты с аннотациями @MockBean, оказывается известная проблема)

2024-04-29 19:05 UTC, QuantuM1o1 commented on bot/pom.xml
> +
Это на следующее дз

2024-04-29 19:05 UTC, QuantuM1o1 commented on bot/src/main/resources/application.yml
> +    - not_found
fixed

2024-04-30 20:00 UTC, iskanred approved these changes
✅

На портале ставлю 6/6 💯

2024-05-01 03:36 UTC, merged