hw8
QuantuM1o1/Tinkoff2024Homeworks pull request #9
Opened 2024-04-07 16:39 UTC by QuantuM1o1

2024-04-25 19:28 UTC, iskanred requested changes
🔥 Здорово сделал, неожиданно с протобафом, а не json) 
Почему так решил, кстати?

Единственное, кейс с невалидными сообщениями какой-то неполный, вдруг будет description, а остального не будет или вообще сообщение битое, оно даже до метода листенера не дойдет и в dlq не попадет.

\+ вообще никаких тестов на кафку не увидел, к сожалению(
Тестов на историю с отправкой в dlq, на консьюмеры и продюсеры
Если сложно и нужно поднимать кафковый тест-контейнер, то мб и не надо, но увидеть хочется хотя бы базу, которую можно замокать. + Тесты на поведение с DLQ увидеть все-таки хотелось бы)

Из-за этого всего пока 4/6 (-1 за отсутствие любых тестов, -1 за отсутствие обработки невалидных сообщений и отправкой в DLQ)

Как обычно, отправил на доработку на портале и на гитхабе)
Жду!)

2024-04-25 19:28 UTC, iskanred commented on bot/src/main/java/edu/java/bot/listener/UpdatesKafkaListener.java
> +        containerFactory = "protobufKafkaListenerContainerFactory"
круто, что на протобафе сделал!

2024-04-25 19:28 UTC, iskanred commented on bot/src/main/java/edu/java/bot/listener/UpdatesKafkaListener.java
> +        if (update.getDescription().isBlank()) {
а если придет невалидное сообщение, которые свалится на десериализации? нужно такой кейс тоже учесть)

смотри, если сообщение невалидное (нет какого-то поля, или по-другому называется, или вообще пустой json), то кафка ошибку кинет не на уровне метода, а за его пределами, попытаясь распарсить сообщение в объект типа LinkUpdateResponse

надо сделать либо кастомный обработчик ошибок и положит в аннотацию @KafkaListener:
https://docs.spring.io/spring-kafka/reference/kafka/annotation-error-handling.html

либо чуть попроще распарсить сообщение в строку (@payload), а дальше уже пытаться его валидировать / парсить и контролировать ошибки самому:
https://docs.spring.io/spring-kafka/reference/kafka/receiving-messages/validation.html
https://stackoverflow.com/questions/46325540/how-to-use-spring-kafkas-acknowledgement-acknowledge-method-for-manual-commit

2024-04-25 19:28 UTC, iskanred commented on bot/src/main/java/edu/java/bot/listener/UpdatesKafkaListener.java
> +            this.updateKafkaTemplate.send("scrapper.update.dlq", update);
я бы тут тоже лог сделал)

2024-04-25 19:28 UTC, iskanred commented on compose.yml
> +      "
это для чего такое надо?)

2024-04-25 19:28 UTC, iskanred commented on compose.yml
>  volumes:
В задании было, кстати, про храние данных кафки в именованном вольюме, но у тебя нет такого

![image](https://github.com/QuantuM1o1/Tinkoff2024Homeworks/assets/37081728/28c1e11e-93cf-4caf-9fed-d24fa9091fa0)

2024-04-25 19:28 UTC, iskanred commented on compose.yml
> +    depends_on:
зукипер моежт стартовать, но еще не быть готовым к действиям, поэтому рекомендую изучать readiness пробы в docker-compose, а именно condition'ы и healthcheck'и 

https://docs.docker.com/compose/startup-order/
https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y

Вероятно, тут оно конкретно не нужно, но просто для информации)

2024-04-25 19:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    String kafkaUrl,
что за кафка урл?)

2024-04-25 19:28 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/UpdateSender.java
> +    }
это, кстати, интересное решение)

оно круто, если ты хочешь переключать флаг в рантайме (и система так устроена, что она позволяет это делать), тогда новые вызовы `sendNotification` пойдут по флоу вызова другого сервиса

Но базово, когда такой флоу не предусматривается и изменение флага должно аффектить только при перезапуске, я бы рекомендовал навешивать `@Conditional...` аннотации на соответсвтующие сервисы и реализовать один интерфейс:

```java
interface BotUpdateSender { void sendUpdate() }

@ConditionalOnHavingValue("useQueue=true")
class KafkaBotUpdateSender { ... }

@ConditionalOnMissinBean(KafkaBotUpdateSender.class)
class RestBotUpdateSender { ... }

class NotificationService {
    private final BotUpdateSender botUpdateSender;
}
```

2024-05-02 16:55 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/listener/UpdatesKafkaListener.java
> +        containerFactory = "protobufKafkaListenerContainerFactory"
На семинаре показывали, решил попробовать

2024-05-02 16:56 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/listener/UpdatesKafkaListener.java
> +        if (update.getDescription().isBlank()) {
Поменял реализацию

2024-05-02 16:56 UTC, QuantuM1o1 commented on bot/src/main/java/edu/java/bot/listener/UpdatesKafkaListener.java
> +            this.updateKafkaTemplate.send("scrapper.update.dlq", update);
Поменял реализацию

2024-05-02 16:56 UTC, QuantuM1o1 commented on compose.yml
> +      "
Убрал

2024-05-02 16:56 UTC, QuantuM1o1 commented on compose.yml
>  volumes:
Добавил

2024-05-02 16:57 UTC, QuantuM1o1 commented on compose.yml
> +    depends_on:
fixed

2024-05-02 16:57 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    String kafkaUrl,
fixed

2024-05-02 16:57 UTC, QuantuM1o1 commented on scrapper/src/main/java/edu/java/service/UpdateSender.java
> +    }
fixed

2024-05-02 18:39 UTC, iskanred approved these changes
Хорошо! Еще если покопаешься с тетсконтейнерами еще чуток и попробуешь завести, огонь будет 🔥

В целом молодец, правки нужные внес 6/6 💯

✅

2024-05-03 15:27 UTC, merged